In [1]:
import nltk
import regex
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances
from sklearn import preprocessing

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
Courpus1 = {'The Punisher is a fictional antihero appearing in American comic books published by Marvel Comics.',
           'The character was created by writer Gerry Conway and artists John Romita Sr. and Ross Andru.',
           'The character is depicted as an Italian-American vigilante who employs murder, kidnapping, extortion, coercion, threats of violence, and torture in his campaign against crime.',
           'Driven by the deaths of his wife and two children, who were killed by the mob for witnessing a killing in New York City\'s Central Park',
           'the Punisher wages a one-man war on crime using various weapons.',}

In [4]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(Courpus1)
print(vectorizer.get_feature_names())
print(X.toarray())

['against', 'american', 'an', 'and', 'andru', 'antihero', 'appearing', 'artists', 'as', 'books', 'by', 'campaign', 'central', 'character', 'children', 'city', 'coercion', 'comic', 'comics', 'conway', 'created', 'crime', 'deaths', 'depicted', 'driven', 'employs', 'extortion', 'fictional', 'for', 'gerry', 'his', 'in', 'is', 'italian', 'john', 'kidnapping', 'killed', 'killing', 'man', 'marvel', 'mob', 'murder', 'new', 'of', 'on', 'one', 'park', 'published', 'punisher', 'romita', 'ross', 'sr', 'the', 'threats', 'torture', 'two', 'using', 'various', 'vigilante', 'violence', 'wages', 'war', 'was', 'weapons', 'were', 'who', 'wife', 'witnessing', 'writer', 'york']
[[0.         0.24241232 0.         0.         0.         0.30046383
  0.30046383 0.         0.         0.30046383 0.20122413 0.
  0.         0.         0.         0.         0.         0.30046383
  0.30046383 0.         0.         0.         0.         0.
  0.         0.         0.         0.30046383 0.         0.
  0.         0.2012

/opt/conda/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


# Euclidean Distance

In [5]:
euclidean_dist = euclidean_distances(X)
squared_euclidean = np.square(euclidean_dist)
print (squared_euclidean)

[[0.         1.73870149 1.82908412 1.89196424 1.76704757]
 [1.73870149 0.         1.8749137  1.79225892 1.6870098 ]
 [1.82908412 1.8749137  0.         1.96085117 1.93662324]
 [1.89196424 1.79225892 1.96085117 0.         1.74225576]
 [1.76704757 1.6870098  1.93662324 1.74225576 0.        ]]


# Cosine Similarity

In [6]:
print(cosine_similarity(X))

[[1.         0.13064926 0.08545794 0.05401788 0.11647622]
 [0.13064926 1.         0.06254315 0.10387054 0.1564951 ]
 [0.08545794 0.06254315 1.         0.01957441 0.03168838]
 [0.05401788 0.10387054 0.01957441 1.         0.12887212]
 [0.11647622 0.1564951  0.03168838 0.12887212 1.        ]]


# Meta Search

In [7]:
import math

jud=int(input("Enter No Of Judges:"))
par=int(input("Enter No Of Participants"))

create_csv=[]

for i in range(par):
    temp=[]
    for j in range(jud):
        print("Enter Rank Given By Judge ",j+1," To Participant ",i+1," :")
        vote=input()
        if (vote==""):
            vote=math.inf
        else:
            vote=int(vote)
        temp.append(vote)
    create_csv.append(temp)
print(create_csv)

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

In [ ]:
df = pd.DataFrame(create_csv) 
df.to_csv('data.csv') 

In [ ]:
print(create_csv)

In [ ]:
print(df)

In [ ]:
Borda=df
Reciprocal=df

for i in range(jud):
    Reciprocal[i]=Reciprocal[i].replace(math.inf,0)
Reciprocal=Reciprocal.values.tolist()

for i in range(jud):
    Borda[i]=Borda[i].replace(math.inf,0)
    data=Borda[i]
    a=0
    count=0
    for j in range(par):
        if data[j]!=0:
            a=a+(par-data[j]+1)
        else:
            count=count+1
    if (count):
        s = sum(range(1, par + 1))
        diff=(s-a)/count
        
    Borda[i]=Borda[i].replace(0,diff)
    
Borda=Borda.values.tolist()

In [ ]:
print(Borda)
print(Reciprocal)

# Borda Method

In [ ]:
ans=[]
for i in range(par):
    a=0
    data=Borda[i]
    for j in range(jud):
        a=a+(par-data[j]+1)
    ans.append(a)
        
    

In [ ]:
print(ans)

# Reciprocal

In [ ]:
ans=[]
for i in range(par):
    a=0
    data=Reciprocal[i]
    for j in range(jud):
        if(data[j]==0):
            continue
        a=a+(1/data[j])
    ans.append(a)

In [ ]:
print(ans)